CodersForLife/Data-Structures-Algorithms

- Searching/Binary-Search.cpp
recursive binary search code in c++
> binary search implemented

- Graphs/BFS.cpp
Fixes #[Add issue number here."First steps for issues #IssueNumber]
Language: [Add here in what language you have implemented this data structure or algorithm.]
> Added BFS in Graphs [C++] Referring issue#15

- Searching/Ternary-Search.cpp
> Ternary Search cpp

- Sorting/Heapsort.cpp
> Add C++ Heap Sort using heap based on Vectors

- Sorting/Selectionsort.cpp
> Added working Selectionsort

- Sorting/QuickSort.java
Fixes #2 (QuickSort)
Language: Java
Algorithm: Quick Sort
> Created Java Quick Sort Implementation

- Sorting/Insertion_sort.py
> Added insertion sort Python implementation

- Trees/Bfs.py
Tested for following cases:
1. Null graph
2. Null Start
3. Invalid Staart
Fixes [https://github.com/CodersForLife/Data-Structures-Algorithms/issues/15](https://github.com/CodersForLife/Data-Structures-Algorithms/issues/15)
Language: Python, BFS
> Added Bfs.py

- Structures/Queue.h
Fixes[#20]
Language: [C++]
Implemented using Templates.
> Simple Queue implementation

- Dijkstra/Dijkstra.cpp.cpp
> Dijkstra cpp

- Arrays/sum.java
Fixes #[46]
Language: [Java, Dynamic Programming]
> Maximum subarray sum using dynamic programming

- Sorting/SelectionSort.java
> Add Selection Sort using Java (Javadoc included)

- Arrays/QueueArray.py
Fixes #54  
Language: python version 3
Sorry for the bug. Now everything is ok!
> Bug fixed. Program crashed when you tryed to dequeue with empty queue

- Arrays/StackArray.py
Fixes #19 
Language: Python version 3
> Stack array

- Sorting/Insertionsort.cpp
Fixes #5 Insertion Sort
Language: C++
> Added working Insertionsort

- Searching/Binary-Search.c
Fixes #[Add issue number here."First steps for issues #IssueNumber]
Language:Binary Search implemented in C
> Binary Search in C

- Graphs/dijkstra.py
Fixes #18 Issue 
Dijkstra v.1.0 for python
Language: Python 3.0
> Issue #18 Fixed  Dijkstra python

- Searching/BinarySearch.java
- Sorting/BubbleSort.java
implemented bubble sort in Java
Fixes #[Add issue number here."First steps for issues #IssueNumber]
Language: [Add here in what language you have implemented this data structure or algorithm.]
> Bubble Sort

- Sorting/MergeSort.java
> Created Java Merge Sort Implementation

- Searching/LinearSearch.py
> Added LinearSearch in Python

- Structures/CircularLinkedList.java
- Structures/DoublyLinkedList.java
- Structures/LinkedList.java
> Linked Lists in java

- Bit manipulation/powerOfTwo.cpp
> Check if number is power of two using bit manipulation

- Structures/LinkedLists/DNode.java
- Structures/LinkedLists/QueueDLinked.java
Fixes #45 
Language: Java 8
I have implemented and tested a queue using a double linked list. I use generics to grant modularity.
> Queue linkedlist

- Structures/LinkedLists/DNode.java
- Structures/LinkedLists/StackDLinked.java
Fixes #44 
Language: Java 8
I have implemented and tested a stack using a double linked list. I use generics to grant modularity.
> Stack linkedlist

- Searching/BinarySearch.py
Fixes #[7."Added Binary Search implementation in Python #7  ]
Language: [ Python ]
> added_binary_search_in_python

- Searching/LinearSearch.js
> Added LinearSearch in JavaScript

- Bit manipulation/IsPowerOfTwo.py
> Added Check for Power of 2 in Python 3

- Sorting/insertionsort.java
Working Java Insertion Sort
Fixes #5
Language: Java
> Created Java Implementation of Insertion Sort

- Sorting/bubblesort.go
Added Bubble Sort in Go language.
> Add Bubble Sort in Go language

- Elemental algorithms/exponentiation.cpp
Fixes https://github.com/CodersForLife/Data-Structures-Algorithms/issues/85
Language: C++
> Added exponentiation by squaring

- Bit manipulation/CheckPowerOfTwo.kt
> Added check for power of 2 in Kotlin

- Graphs/Kruskal.cpp
- Graphs/Prim.cpp
- Graphs/TopologicalSort.cpp
> Topological Sort .cpp

- Sorting/bucketsort.c
> Bucketsort c implementation

- Bit manipulation/powerOfTwo.js
> Add check for power of 2 in JS

- .github/PULL_REQUEST_TEMPLATE
- CONTRIBUTING.md
- LICENSE.md
- README.md
As discussed on the marked issue, I've added the new structure for naming implementation Pull Requests.
- CONTRIBUTING.md was expanded, containing more information for future contributors and to allow easier reviewing by the repository maintainers.
- LICENSE.md was also added.
- I have also changed the PR template to include a checklist on the new contribution guidelines.
- README.md was also updated with these changes.
Issue #82 
If any more changes are need, just let me know.
> Contribution Guidelines, License and PR model.

- Sorting/CountingSort.cpp
> Added Counting Sort using C++

- Bit manipulation/CheckPowerOfTwo.c
> Added check for power of 2 in C

- Searching/BinarySearch.js
Fixes #7 
Language: JavaScript
> Added BinarySearch in JavaScript

- Graphs/Kruskal.cpp
- Graphs/Prim.cpp
- Graphs/TopologicalSort.cpp
> Kruskal And Prim's Algorithm

- Sorting/Quick_sort.py
> Added Python Quick Sort Implementation

- Searching/TernarySearch.py
> Ternary Search added in Python3

- Sorting/SelectionSortAlt.cpp
Fixes #4 
Language: cpp
Implements a selection sort with ability to sort in both ascending and descending order.
Hope I'm not breaking any rules by submitting the same sorting algorithm as someone else in the same language.
> Alternative selection sort in cpp

- Sorting/MergeSort.js
Fixes #123. "First steps for issues #123" 
Language: Javascript
This PR adds mergesort in javascript
> Created MergeSort.js

- Graphs/DSU.cpp
Fixes: A good to have in collection algo, the disjoint set algo. This is basic use of it for counting number of components
Language: c++
> Number of Components by Disjoint Set Algo

- Sorting/mergesort.c
Fixes https://github.com/CodersForLife/Data-Structures-Algorithms/issues/110
Language: C
> Added mergesort in C

- Graphs/Kruskal.cpp
- Graphs/Prim.cpp
- Graphs/TopologicalSort.cpp
- Segment Tree/SegmentTree.cpp
> Segment Tree

- Arrays/MaxSubarraySum.cpp
> C++: max subarray sum in DP

- Trees/Right View Binary Tree
> right view bt

- Trees/Left view binary tree
> left view bt

- Trees/Child Sum Java
- Trees/Left view binary tree
Issue #[Add issue number here.]
> Child Sum Binary Tree

- Trees/Child Sum Java
- Trees/Left view binary tree
- Trees/Mirror Tree
Issue #[Add issue number here.]
> Mirror Tree

- Sorting/SelectionSort.js
Fixes #125 .First steps for issues #125 #4 
Language: Javascript
Added SelectionSort in Javascript.
> Created SelectionSort in Javascript

- Structures/LinkedList.cpp
Implemented linked list in c++ (tested)
Issue #265
> implemented linked list in cpp (tested)

- Trees/MinMax tree
> Minmax for Tree #193

- Graphs/FloydWarshall.cpp
> Floyd Warshall's Algorithm in c++

- Arrays/FourSum.cpp
> four sum added

- Arrays/Buy And Sell Stocks 3.cpp
Added Buy & Sell Stocks 3 problem.
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/
Issue #309
> added Buy & Sell stock 3

- Arrays/Buy And Sell Stocks 1.cpp
> added Buy & Sell stock 1

- Arrays/Buy And Sell Stocks 2.cpp
Added Buy & Sell stocks 2
Issue #313
> added Buy & Sell stock 2

- Arrays/First&LastPositionElementSortedArray.cpp
First & Last element in a sorted rotated array.
Issue #315
> First & Last element in sorted Array
